Repository IT-dda/Pocus_WebView, pull requests merged in 2022-05, with the labels that each got.

#2 pr test
  src/static/css/variable.css
Labels: 기능

#13 Git&GitHub 사용법 문서 정리를 위한 test PR
  README.md
Labels: 문서

#15 Frontend 코드 리뷰 - mypage, login 파트
  src/static/css/home/login.css
  src/static/css/home/mypage.css
  src/views/home/login.ejs
  src/views/home/mypage.ejs
Labels: 코드리뷰

#16 회원가입 UI
  src/static/css/home/login.css
  src/static/css/home/register.css
  src/views/common/header.ejs
  src/views/home/login.ejs
  src/views/home/register.ejs
Labels: 디자인

#17 Feat: DB DDL 및 DML 테스트
  src/sql/pocus_ddl.sql
  src/sql/pocus_dml.sql
Labels: 개발
