Repository IT-dda/Pocus_WebView, pull requests merged in 2022-06, with the labels that each got.

#19 로그인&회원가입 기능 구현
  app.js
  package-lock.json
  package.json
  sessions/OV07_Pl8Mn9zxG6UykvwWExBf0ig_YKB.json
  src/config/database.js
  src/controllers/home.ctrl.js
  src/routes/index.js
  src/static/css/pages/login.css
  src/views/common/header.ejs
  src/views/pages/index.ejs
  src/views/pages/init.ejs
  src/views/pages/login.ejs
  src/views/pages/mypage.ejs
  src/views/pages/pocus.ejs
  src/views/pages/register.ejs
Labels: 기능, 개발

#20 로그인, 회원가입 기능 구현 - session, flash() 이용
  .gitignore
  app.js
  package-lock.json
  package.json
  src/config/database.js
  src/controllers/home.ctrl.js
  src/sql/pocus_ddl.sql
  src/static/css/common/header.css
  src/static/css/pages/login.css
  src/views/common/header.ejs
  src/views/pages/index.ejs
  src/views/pages/init.ejs
  src/views/pages/login.ejs
  src/views/pages/mypage.ejs
  src/views/pages/pocus.ejs
  src/views/pages/register.ejs
Labels: 기능, 개발

#21 Init, Pocus UI
  package-lock.json
  sessions/OV07_Pl8Mn9zxG6UykvwWExBf0ig_YKB.json
  src/static/css/common.css
  src/static/css/pages/init.css
  src/static/css/pages/pocus.css
  src/static/css/variable.css
  src/static/image/posture.jpeg
  src/static/js/init.js
  src/static/js/pocus.js
  src/views/common/header.ejs
  src/views/include.ejs
  src/views/pages/init.ejs
  src/views/pages/pocus.ejs
Labels: 기능, 디자인

#22 Fix: 로그인, 회원가입 오류 수정
  src/controllers/home.ctrl.js
  src/views/pages/login.ejs
  src/views/pages/mypage.ejs
  src/views/pages/register.ejs
Labels: 기능, 개발

#23 Fix: main getstart 버튼 연결, header 메뉴 목록 수정
  src/static/js/main.js
  src/views/common/header.ejs
  src/views/pages/main.ejs
Labels: 버그, 개발
